#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N smk_trinity_abudances_only
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=8GB,ncpus=1
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Source env modules and paths"
cd /g/data/pq84/malaria/Pk_trancsriptomics/smk_trinity_unique_trans
source /g/data/pq84/malaria/Pk_trancsriptomics/smk_rna_denovo_assmebly/activate_pipeline_env.sh

echo "---------------------------------------"
echo "Start snakemake pipeline"
snakemake --profile config/pbs-submission/ --keep-going --latency-wait 10 --snakefile Snakefile

echo "---------------------------------------"
echo "Pipeline finished"
